---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Kafka production deployment'

Parameters:
  CfnS3Bucket:
    Type: String
    Default: kafka-live-cfn
    Description: S3 bucket name of the rds cloudformation template located.
  EnvironmentName:
    Type: String
    Default: KafkaProd01

Resources:
  # null resource for testing purposes.
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle

  VpcStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL:
        Fn::Sub:
          - https://${cfnBucketName}.s3-ap-southeast-1.amazonaws.com/${childStackName}/${cfnTemplateName}.yaml
          - cfnBucketName: !Ref CfnS3Bucket
            childStackName: vpc
            cfnTemplateName: vpc
      Parameters:
        EnvironmentName: !Ref EnvironmentName
  
  Ec2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub:
          - https://${cfnBucketName}.s3-ap-southeast-1.amazonaws.com/${childStackName}/${cfnTemplateName}.yaml
          - cfnBucketName: !Ref CfnS3Bucket
            childStackName: ec2
            cfnTemplateName: ec2
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        BastionHostSubnetIds: !GetAtt VpcStack.Outputs.BastionHostSubnetIds
        BastionHostSubnetAzs: !GetAtt VpcStack.Outputs.BastionHostSubnetAzs
